/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LoginRegisterCont;
import controllers.MenuBarCont;
import controllers.UserCont;
import java.awt.Color;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.UserMDL;

/**
 *
 * @author mones
 */
public class ProgV extends javax.swing.JFrame {
    private String pageName= "prog";
    /**
     * Creates new form progV
     */
    public ProgV() {
        initComponents();
        setSize(414,667);
        
        //dlgHistBtn.addActionListener(new MenuBarCont(this));//UserCont(this));
        //MenuBarView menu = new MenuBarView();
        //this.setContentPane(menu.getContentPane());
        //menu.setPageTitle("Progress View");
        //menu.setPageTopicContent(ProgViewContent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgHistBtn = new javax.swing.JButton();
        ProgViewContent = new javax.swing.JPanel();
        nameP = new javax.swing.JLabel();
        userIdP = new javax.swing.JLabel();
        groupIdP = new javax.swing.JLabel();
        emailP = new javax.swing.JLabel();
        userTypeP = new javax.swing.JLabel();
        pointsJB = new javax.swing.JLabel();
        iconLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        currentLvlP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        dlgHistBtn.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        dlgHistBtn.setText("View Dialogue History");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProgViewContent.setBackground(new java.awt.Color(255, 255, 255));
        ProgViewContent.setPreferredSize(new java.awt.Dimension(414, 515));

        nameP.setText("name");

        userIdP.setText("userId");

        groupIdP.setText("groupId");

        emailP.setText("email");

        userTypeP.setText("user Type");

        pointsJB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pointsJB.setForeground(new java.awt.Color(0, 153, 255));
        pointsJB.setLabelFor(iconLbl);
        pointsJB.setText("Points");
        pointsJB.setToolTipText("");

        iconLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GreyPieIcon.png"))); // NOI18N
        iconLbl.setFocusable(false);
        iconLbl.setPreferredSize(new java.awt.Dimension(220, 220));
        iconLbl.setRequestFocusEnabled(false);
        iconLbl.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel2.setText("UserId:");

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel3.setText("GroupId:");

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel5.setText("User Type:");

        currentLvlP.setText("Current Level: B1");

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 0, 14)); // NOI18N
        jLabel6.setText("Current Level:");

        javax.swing.GroupLayout ProgViewContentLayout = new javax.swing.GroupLayout(ProgViewContent);
        ProgViewContent.setLayout(ProgViewContentLayout);
        ProgViewContentLayout.setHorizontalGroup(
            ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgViewContentLayout.createSequentialGroup()
                .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(pointsJB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgViewContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgViewContentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentLvlP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(ProgViewContentLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userIdP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nameP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userTypeP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(groupIdP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        ProgViewContentLayout.setVerticalGroup(
            ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgViewContentLayout.createSequentialGroup()
                .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgViewContentLayout.createSequentialGroup()
                                .addComponent(pointsJB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))))
                    .addGroup(ProgViewContentLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameP))
                        .addGap(18, 18, 18)
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(userIdP))
                        .addGap(18, 18, 18)
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(groupIdP))
                        .addGap(18, 18, 18)
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(emailP))
                        .addGap(18, 18, 18)
                        .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(userTypeP))))
                .addGap(84, 84, 84)
                .addGroup(ProgViewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentLvlP)
                    .addComponent(jLabel6))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProgViewContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProgViewContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public ProgV(UserMDL user) {
        initComponents();
        setSize(414,667);
        nameP.setText(user.getSurname());
        userIdP.setText(user.getUserID());
        groupIdP.setText(user.getGroupID());
        emailP.setText(user.getEmail());
        userTypeP.setText(user.getUserType());
        currentLvlP.setText(user.getLangLvl());
       pointsJB.setText(Integer.toString(user.getProgPoints()));
        
//BufferedImage myPicture = ImageIO.read(new File("C:\\\\Users\\\\New User\\\\Documents\\\\GitHub\\\\GroupE_CW_Project\\\\PolyGlot\\\\src\\\\image"));
//JLabel picLabel = new JLabel(new ImageIcon(myPicture));
//add(picLabel); 
 
    }

    public JPanel getProgViewContent() {
        return ProgViewContent;
    }

    public JButton getDlgHistBtn() {
        return dlgHistBtn;
    }

   /* public JPanel getDataGraph() {
        return DataGraph;
    }*/

    public JLabel getCurrentLvlP() {
        return currentLvlP;
    }

    public JLabel getEmailP() {
        return emailP;
    }

    public JLabel getGroupIdP() {
        return groupIdP;
    }

    public JLabel getNameP() {
        return nameP;
    }


    public JLabel getUserIdP() {
        return userIdP;
    }

    public JLabel getUserTypeP() {
        return userTypeP;
    }
    

    public void setDlgHistBtn(JButton dlgHistBtn) {
        this.dlgHistBtn = dlgHistBtn;
    }
    
    /* public void setDataGraph(JPanel DataGraph) {
       this.DataGraph = DataGraph;
        Icon icon= createImageIcon("/GreyPieIcon.png","pie icon");
        iconLbl.add(pointsJB);
    }*/

    public void setCurrentLvlP(JLabel currentLvlP) {
        this.currentLvlP = currentLvlP;
    }

    public void setEmailP(JLabel emailP) {
        this.emailP = emailP;
    }

    public void setGroupIdP(JLabel groupIdP) {
        this.groupIdP = groupIdP;
    }

    public void setNameP(JLabel nameP) {
        this.nameP = nameP;
    }

    public void setUserIdP(JLabel userIdP) {
        this.userIdP = userIdP;
    }

    public void setUserTypeP(JLabel userTypeP) {
        this.userTypeP = userTypeP;
    }
    

    /**by Aisana (w1775375)
     * Method used to find and return image from resource file
     * @param path - string to pass image name
     * @param description - string used to describe the icon in case needed to be used, will be attached to the image
     * @return returns imageIcon you can use to setIcon for a button or label
     */
    public ImageIcon createImageIcon(String path,
                                           String description) {
        java.net.URL imgURL = MenuBarV.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProgViewContent;
    private javax.swing.JLabel currentLvlP;
    private javax.swing.JButton dlgHistBtn;
    private javax.swing.JLabel emailP;
    private javax.swing.JLabel groupIdP;
    private javax.swing.JLabel iconLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameP;
    private javax.swing.JLabel pointsJB;
    private javax.swing.JLabel userIdP;
    private javax.swing.JLabel userTypeP;
    // End of variables declaration//GEN-END:variables
}
