
package views;

import controllers.LoginRegisterCont;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import models.UserMDL;

public class SettingV extends javax.swing.JFrame {

    ArrayList<String> langList= new ArrayList<String>();
    String langName;
    String langid;
    UserMDL userMDL;
    public SettingV(UserMDL userMDL) {
        initComponents();
        addinglang();
        this.userMDL = userMDL;
        setSelectedLang(userMDL);
        colorRedBttn(this.logoutBttn, "Logout");
    }

//    public SettingV(MenuBarV menu) {
//        initComponents();
//        addinglang();
//        //getSelectLang().setSelectedItem(langChoice);
//        this.getLogoutBttn().addActionListener(new LoginRegisterCont(this,menu)); //By Monesha
//        this.getSelectLang().addActionListener(new LoginRegisterCont(this,menu));
//    }

//    public SettingV(MenuBarV menuBar, LoginRegisterCont logCont) {
//        initComponents();
//        addinglang();
//        //getSelectLang().setSelectedItem(langChoice);
//        //logCont.setAccRec(this, menuBar);
//        this.getLogoutBttn().addActionListener(logCont); //By Monesha
//        this.getSelectLang().addActionListener(logCont);
//    }
    
    public void setContListener(LoginRegisterCont logCont) 
    {
        this.getLogoutBttn().addActionListener(logCont); //By Monesha
        this.getSelectLang().addActionListener(logCont);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingContent = new javax.swing.JPanel();
        settingLabel = new javax.swing.JLabel();
        selectLang = new javax.swing.JComboBox<>();
        logoutBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SettingContent.setBackground(new java.awt.Color(255, 255, 255));
        SettingContent.setPreferredSize(new java.awt.Dimension(414, 515));

        settingLabel.setFont(new java.awt.Font("Dialog", 1, 23)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(121, 121, 121));
        settingLabel.setText("Choose language of study: ");

        selectLang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectLang.setForeground(new java.awt.Color(121, 121, 121));
        selectLang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(121, 121, 121)));
        selectLang.setMinimumSize(new java.awt.Dimension(72, 28));
        selectLang.setPreferredSize(new java.awt.Dimension(72, 28));

        logoutBttn.setBackground(new java.awt.Color(238, 105, 94));
        logoutBttn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        logoutBttn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBttn.setText("Logout");
        logoutBttn.setPreferredSize(new java.awt.Dimension(193, 56));

        javax.swing.GroupLayout SettingContentLayout = new javax.swing.GroupLayout(SettingContent);
        SettingContent.setLayout(SettingContentLayout);
        SettingContentLayout.setHorizontalGroup(
            SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingContentLayout.createSequentialGroup()
                .addGroup(SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingContentLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SettingContentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectLang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        SettingContentLayout.setVerticalGroup(
            SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingContentLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectLang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(logoutBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SettingContent, 380, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setSelectedLang(UserMDL userMDL){
        getSelectLang().setSelectedItem(userMDL.getApplang());
    }
    
    //Populating The langList
    private void addinglang(){ 
        //ArrayList<String> langList = new UserMDL().getLangList();
        langList.add("French");
        langList.add("Spanish");
        for (int i = 0; i < langList.size(); i++) {
            selectLang.addItem(langList.get(i));
            //System.out.println(langList.get(i)+"!!!");
        }
    }

    public void changeLangOrder(String langChoice) {
        int position;
        if (getLangList().contains(langChoice)) {
            position = getLangList().indexOf(langChoice);

            String originalStr = getLangList().get(0);
            getLangList().set(position, originalStr);
            getLangList().set(0, langChoice);
        }
    }

    
    public ArrayList<String> getLangList() {
        return langList;
    }
         
    public JPanel getSettingContent() {
        return SettingContent;
    }

    public JButton getLogoutBttn() {
        return logoutBttn;
    }

    public void setLogoutBttn(JButton logoutBttn) {
        this.logoutBttn = logoutBttn;
    }
    
    public JComboBox<String> getSelectLang() {
        return selectLang;
    }

    public void setSelectLang(JComboBox<String> selectLang) {
        this.selectLang = selectLang;
    }
    
    public void colorRedBttn(JButton bttn, String bttnName){
        
        bttn.setBackground(new java.awt.Color(238, 105, 94));
        bttn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bttn.setForeground(new java.awt.Color(255, 255, 255));
        bttn.setText(bttnName);
        bttn.setContentAreaFilled(true);
        
        //bttn.setBorderPainted(false);
        //bttn.setFocusPainted(false);
        //bttn.setIgnoreRepaint(true);
        //bttn.repaint();
        //bttn.revalidate();
        //bttn.setMinimumSize(new java.awt.Dimension(168, 46));

    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SettingContent;
    private javax.swing.JButton logoutBttn;
    private javax.swing.JComboBox<String> selectLang;
    private javax.swing.JLabel settingLabel;
    // End of variables declaration//GEN-END:variables

}
