/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LoginRegisterCont;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author mones
 */
public class SettingV extends javax.swing.JFrame {

    /**
     * Creates new form SettingV
     */
    public SettingV() {
        initComponents();
        
//       MenuBarV  menu = new MenuBarV();
//        this.setContentPane(menu.getContentPane());
//        menu.setPageTitle("Setting");
//        menu.setPageTopicContent(SettingContent);

        //this.logoutBttn.addActionListener(new LoginRegisterCont(this));
        
        //setSize(414,667);
        //MenuBarView menu = new MenuBarView();
        //this.setContentPane(menu.getContentPane());
        //menu.setPageTitle("Setting");
        //menu.setPageTopicContent(SettingContent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingContent = new javax.swing.JPanel();
        settingLabel = new javax.swing.JLabel();
        selectLang = new javax.swing.JComboBox<>();
        logoutBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SettingContent.setBackground(new java.awt.Color(255, 255, 255));
        SettingContent.setPreferredSize(new java.awt.Dimension(414, 515));

        settingLabel.setText("Choose language of study: ");

        selectLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logoutBttn.setText("Logout");
        logoutBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingContentLayout = new javax.swing.GroupLayout(SettingContent);
        SettingContent.setLayout(SettingContentLayout);
        SettingContentLayout.setHorizontalGroup(
            SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingContentLayout.createSequentialGroup()
                .addGroup(SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingContentLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(settingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(selectLang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SettingContentLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(logoutBttn)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        SettingContentLayout.setVerticalGroup(
            SettingContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingContentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(settingLabel)
                .addGap(18, 18, 18)
                .addComponent(selectLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(logoutBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SettingContent, 380, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SettingContent, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBttnActionPerformed


    public JPanel getSettingContent() {
        return SettingContent;
    }

    public JButton getLogoutBttn() {
        return logoutBttn;
    }

    public void setLogoutBttn(JButton logoutBttn) {
        this.logoutBttn = logoutBttn;
    }
    
    public JComboBox<String> getSelectLang() {
        return selectLang;
    }

    public void setSelectLang(JComboBox<String> selectLang) {
        this.selectLang = selectLang;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SettingContent;
    private javax.swing.JButton logoutBttn;
    private javax.swing.JComboBox<String> selectLang;
    private javax.swing.JLabel settingLabel;
    // End of variables declaration//GEN-END:variables
}
