/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.LoginRegisterCont;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author Joshua
 */
public class SupportV2 extends javax.swing.JFrame {

    
     //Creates new form SupportV2
     
    public SupportV2() {
        initComponents();
        //Back to register and back to login
        this.backBttnR.addActionListener(new LoginRegisterCont(this));
        this.backBttnL.addActionListener(new LoginRegisterCont(this));
        mainTextField();
        mainTitle();
        colorWhiteBttn(backBttnL, "Back to Login");
        colorWhiteBttn(backBttnR, "Back to Register");
    }
    
    //Title for the JLabel
    
        public void mainTitle() {
        String title1 = "Forgot password?";
        jLabel1.setText(title1);
        
        String title2 = "Contact us";
        jLabel2.setText(title2);
        
        String title3 = "What is this application?";
        jLabel3.setText(title3);
        
        String title4 = "Special thanks to";
        jLabel4.setText(title4);
    }
    
    //Text for populating the textfield
    public void mainTextField() {
        String text1 = "Contact one of the PolyGlot devs via their (fake) emails below";
        jTextArea1.setText(text1);
        jTextArea1.setEditable(false);
        //setEditable to stop users from writing into the field
        
        String text2 = "Zain Cheema (w12345678@my.westminster.ac.uk)\n\n" +
        "Monesha Dhali (w12345679@my.westminster.ac.uk)\n\n" +
        "Rafael Sally (w12345670@my.westminster.ac.uk)\n\n" +
        "Rahat Amit Haider (w12345681@my.westminster.ac.uk)\n\n" +
        "Joshua Nwachukwu (w12345682@my.westminster.ac.uk)\n\n" +
        "Aisana Zharmagambetova (w12345683@my.westminster.ac.uk)";
        jTextArea2.setText(text2);
        jTextArea2.setEditable(false);
        
        String text3 = "This application is a simple language learning app made "
                + "by students in the University of Westminster.\n\n"
                + "It's purpose is to hopefully teach people how to learn "
                + "(at the moment) French and Spanish.";
        jTextArea3.setText(text3);
        jTextArea3.setEditable(false);
        
        String text4 = "Rolf, our tutor and the friends we made along the way";
        jTextArea4.setText(text4);
        jTextArea4.setEditable(false);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supportContent = new javax.swing.JPanel();
        supContTxtScrollP = new javax.swing.JScrollPane();
        SupportContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        helpTitle = new javax.swing.JLabel();
        backBttnL = new javax.swing.JButton();
        backBttnR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supportContent.setPreferredSize(new java.awt.Dimension(414, 480));

        supContTxtScrollP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        supContTxtScrollP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        supContTxtScrollP.setPreferredSize(new java.awt.Dimension(414, 470));

        SupportContent.setBackground(new java.awt.Color(135, 178, 240));
        SupportContent.setAutoscrolls(true);
        SupportContent.setPreferredSize(new java.awt.Dimension(414, 1000));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(121, 121, 121));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(121, 121, 121));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(121, 121, 121));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");

        jScrollPane4.setForeground(new java.awt.Color(121, 121, 121));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(121, 121, 121));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        helpTitle.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        helpTitle.setForeground(new java.awt.Color(255, 255, 255));
        helpTitle.setText("Support Page");

        backBttnL.setText("Back to Login");
        backBttnL.setBorderPainted(false);
        backBttnL.setContentAreaFilled(false);
        colorLoginBttn(backBttnL, "Back to Login");

        backBttnR.setText("Back to Register");
        backBttnR.setBorderPainted(false);
        backBttnR.setContentAreaFilled(false);
        colorRegisterBttn(backBttnR, "Back to Register");
        backBttnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBttnRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SupportContentLayout = new javax.swing.GroupLayout(SupportContent);
        SupportContent.setLayout(SupportContentLayout);
        SupportContentLayout.setHorizontalGroup(
            SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportContentLayout.createSequentialGroup()
                .addGroup(SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SupportContentLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(helpTitle))
                    .addGroup(SupportContentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SupportContentLayout.createSequentialGroup()
                                .addComponent(backBttnL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backBttnR))
                            .addComponent(jLabel1)
                            .addGroup(SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        SupportContentLayout.setVerticalGroup(
            SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(helpTitle)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(SupportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBttnL)
                    .addComponent(backBttnR))
                .addGap(25, 25, 25))
        );

        supContTxtScrollP.setViewportView(SupportContent);

        javax.swing.GroupLayout supportContentLayout = new javax.swing.GroupLayout(supportContent);
        supportContent.setLayout(supportContentLayout);
        supportContentLayout.setHorizontalGroup(
            supportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supContTxtScrollP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        supportContentLayout.setVerticalGroup(
            supportContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supContTxtScrollP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supportContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supportContent, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBttnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBttnRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBttnRActionPerformed

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public JTextArea getjTextArea2() {
        return jTextArea2;
    }

    public JTextArea getjTextArea3() {
        return jTextArea3;
    }

    public JTextArea getjTextArea4() {
        return jTextArea4;
    }

    public JButton getBackBttnL() {
        return backBttnL;
    }

    public JButton getBackBttnR() {
        return backBttnR;
    }

       
    
    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public void setjTextArea2(JTextArea jTextArea2) {
        this.jTextArea2 = jTextArea2;
    }

    public void setjTextArea3(JTextArea jTextArea3) {
        this.jTextArea3 = jTextArea3;
    }

    public void setjTextArea4(JTextArea jTextArea4) {
        this.jTextArea4 = jTextArea4;
    }

    /**
     * Suggested by Aisana(w1775375) will change button look to be white with
     * blue font
     *
     * @param bttn - select button the design of which you want to change
     * @param bttnName - add text to be in that button
     */
    public void colorWhiteBttn(JButton bttn, String bttnName) {
        bttn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn.setBackground(new java.awt.Color(238, 238, 238));
        bttn.setForeground(new java.awt.Color(93, 150, 234));
        bttn.setText(bttnName);
        bttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 152, 224), 1, true));
        bttn.setMinimumSize(new java.awt.Dimension(168, 46));
        bttn.setBorderPainted(true);
        bttn.setContentAreaFilled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    
    //reused and modified code from RegisterV
    public void colorLoginBttn(JButton bttn, String bttnName) {
        bttn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn.setBackground(new java.awt.Color(238, 238, 238));
        bttn.setForeground(new java.awt.Color(93, 150, 234));
        bttn.setText(bttnName);
        bttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 152, 224), 1, true));
        bttn.setMinimumSize(new java.awt.Dimension(168, 46));
        bttn.setBorderPainted(true);
        bttn.setContentAreaFilled(true);
    }
    
    public void colorRegisterBttn(JButton bttn, String bttnName) {
        bttn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn.setBackground(new java.awt.Color(238, 238, 238));
        bttn.setForeground(new java.awt.Color(93, 150, 234));
        bttn.setText(bttnName);
        bttn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(67, 152, 224), 1, true));
        bttn.setMinimumSize(new java.awt.Dimension(168, 46));
        bttn.setBorderPainted(true);
        bttn.setContentAreaFilled(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SupportContent;
    private javax.swing.JButton backBttnL;
    private javax.swing.JButton backBttnR;
    private javax.swing.JLabel helpTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JScrollPane supContTxtScrollP;
    private javax.swing.JPanel supportContent;
    // End of variables declaration//GEN-END:variables
}
