/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.UserMDL;

/**
 *
 * @author mones Joshua
 */
public class UListStdV extends javax.swing.JFrame {

    /**
     * Creates new form UListStdV
     */
    public UListStdV() {
        initComponents();
        setSize(414,667);
        MenuBarV menu = new MenuBarV();
        this.setContentPane(menu.getContentPane());
        menu.setPageTitle("User List");
        menu.setPageTopicContent(UListContent);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UListContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblofStd = new javax.swing.JTable();
        GroupIdLbl = new javax.swing.JLabel();
        GroupTeach = new javax.swing.JLabel();
        GroupTeach1 = new javax.swing.JLabel();
        GroupIdLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UListContent.setBackground(new java.awt.Color(255, 255, 255));
        UListContent.setMinimumSize(new java.awt.Dimension(414, 550));
        UListContent.setPreferredSize(new java.awt.Dimension(414, 550));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        TblofStd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TblofStd.setForeground(new java.awt.Color(135, 178, 240));
        TblofStd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Student Names"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblofStd.setRowMargin(2);
        TblofStd.setSelectionBackground(new java.awt.Color(135, 178, 240));
        TblofStd.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TblofStd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblofStd);
        TblofStd.getTableHeader().setForeground(new Color(255, 255, 255));
        TblofStd.getTableHeader().setBackground(new Color(135, 178, 240));

        GroupIdLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GroupIdLbl.setForeground(new java.awt.Color(121, 121, 121));
        GroupIdLbl.setText("GroupID:");

        GroupTeach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GroupTeach.setForeground(new java.awt.Color(121, 121, 121));
        GroupTeach.setText("Teacher :");

        GroupTeach1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GroupTeach1.setForeground(new java.awt.Color(121, 121, 121));
        GroupTeach1.setText("Mr Pumpkin");

        GroupIdLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GroupIdLbl1.setForeground(new java.awt.Color(121, 121, 121));
        GroupIdLbl1.setText("group102");

        javax.swing.GroupLayout UListContentLayout = new javax.swing.GroupLayout(UListContent);
        UListContent.setLayout(UListContentLayout);
        UListContentLayout.setHorizontalGroup(
            UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UListContentLayout.createSequentialGroup()
                .addGroup(UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UListContentLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GroupIdLbl)
                            .addComponent(GroupTeach))
                        .addGap(18, 18, 18)
                        .addGroup(UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GroupIdLbl1)
                            .addComponent(GroupTeach1)))
                    .addGroup(UListContentLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        UListContentLayout.setVerticalGroup(
            UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UListContentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GroupIdLbl)
                    .addComponent(GroupIdLbl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GroupTeach)
                    .addComponent(GroupTeach1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UListContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UListContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getGroupIdLbl1() {
        return GroupIdLbl1;
    }

    public JLabel getGroupTeach1() {
        return GroupTeach1;
    }

    public JTable getTblofStd() {
        return TblofStd;
    }

    public void setGroupIdLbl1(JLabel GroupIdLbl1) {
        this.GroupIdLbl1 = GroupIdLbl1;
    }

    public void setGroupTeach1(JLabel GroupTeach1) {
        this.GroupTeach1 = GroupTeach1;
    }

    public void setTblofStd(JTable TblofStd) {
        this.TblofStd = TblofStd;
    }

    public JPanel getUListContent() {
        return UListContent;
    }

    public void setUListContent(JPanel UListContent) {
        this.UListContent = UListContent;
    }
    
    /**
     * @param args the command line arguments
     */
    
    //reused and modified code from UListTchV
    
    public void fillTable()
    {
        UserMDL.getConnection();
        ArrayList<String> resultQuery = UserMDL.queryData("SELECT user_name, user_sname FROM User WHERE user_type = 'Student'");
       
        String[] stdName = {"Student First Name", "Student Surname"};
        int row = resultQuery.size()/stdName.length;
        String[][] data = new String[row][stdName.length];
        
        int count = 0;
        for (int i = 0; i < data.length; i++) 
        {
            for (int j = 0; j < stdName.length; j++) 
            {
                data[i][j] = resultQuery.get(count);
                count++;
            }
            
        }
        
        DefaultTableModel td = new DefaultTableModel(data, stdName)
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
                    
        };
        getTblofStd().setModel(td);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GroupIdLbl;
    private javax.swing.JLabel GroupIdLbl1;
    private javax.swing.JLabel GroupTeach;
    private javax.swing.JLabel GroupTeach1;
    private javax.swing.JTable TblofStd;
    private javax.swing.JPanel UListContent;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
    
}