/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.UserCont;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import models.UserMDL;

/**
 * 
 * @author Monesha and Rahat Amit
 */
public class UListTchV extends javax.swing.JFrame {

    /**
     * Creates new form UListTchV
     */
    public UListTchV() 
    {
        initComponents();
        fillTable();
        fillCombo();
        
        this.groupFilterCbox.addActionListener(new UserCont(this));
        this.sortCbox.addActionListener(new UserCont(this));
        this.userLvlFilterCbox.addActionListener(new UserCont(this));
        this.resetBttn.addActionListener(new UserCont(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userListContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblofStd = new javax.swing.JTable();
        orderByLbl = new javax.swing.JLabel();
        userLvlLbl = new javax.swing.JLabel();
        groupSelectLbl = new javax.swing.JLabel();
        groupFilterCbox = new javax.swing.JComboBox<>();
        userLvlFilterCbox = new javax.swing.JComboBox<>();
        sortCbox = new javax.swing.JComboBox<>();
        resetBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userListContent.setBackground(new java.awt.Color(255, 255, 255));
        userListContent.setMinimumSize(new java.awt.Dimension(414, 550));
        userListContent.setPreferredSize(new java.awt.Dimension(414, 550));

        TblofStd.setForeground(new java.awt.Color(29, 91, 161));
        TblofStd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Student Names"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblofStd.setPreferredSize(new java.awt.Dimension(225, 1000));
        TblofStd.setSelectionBackground(new java.awt.Color(135, 178, 240));
        TblofStd.setSurrendersFocusOnKeystroke(true);
        TblofStd.getTableHeader().setReorderingAllowed(false);
        TblofStd.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(TblofStd);
        TblofStd.getTableHeader().setForeground(new Color(255, 255, 255));
        TblofStd.getTableHeader().setBackground(new Color(135, 178, 240));

        orderByLbl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        orderByLbl.setForeground(new java.awt.Color(121, 121, 121));
        orderByLbl.setText("Order by:");

        userLvlLbl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        userLvlLbl.setForeground(new java.awt.Color(121, 121, 121));
        userLvlLbl.setText("Choose user lvl");

        groupSelectLbl.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        groupSelectLbl.setForeground(new java.awt.Color(121, 121, 121));
        groupSelectLbl.setText("Choose group");

        groupFilterCbox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        groupFilterCbox.setForeground(new java.awt.Color(121, 121, 121));
        groupFilterCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select group" }));

        userLvlFilterCbox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        userLvlFilterCbox.setForeground(new java.awt.Color(121, 121, 121));
        userLvlFilterCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select level" }));

        sortCbox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        sortCbox.setForeground(new java.awt.Color(121, 121, 121));
        sortCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select points", "points (lowest)", "points (highest)" }));

        resetBttn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        resetBttn.setForeground(new java.awt.Color(121, 121, 121));
        resetBttn.setText("Reset");

        javax.swing.GroupLayout userListContentLayout = new javax.swing.GroupLayout(userListContent);
        userListContent.setLayout(userListContentLayout);
        userListContentLayout.setHorizontalGroup(
            userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userListContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userListContentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(userListContentLayout.createSequentialGroup()
                        .addComponent(orderByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resetBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userListContentLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(groupSelectLbl))
                            .addGroup(userListContentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userLvlLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(groupFilterCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLvlFilterCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        userListContentLayout.setVerticalGroup(
            userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userListContentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupSelectLbl)
                    .addComponent(orderByLbl)
                    .addComponent(groupFilterCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userListContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLvlFilterCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLvlLbl)
                    .addComponent(resetBttn))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userListContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userListContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getSortCbox() {
        return sortCbox;
    }

    public JTable getTblofStd() {
        return TblofStd;
    }

    public JComboBox<String> getULvlFilterCbox() {
        return userLvlFilterCbox;
    }

    public JComboBox<String> getGroupFilterCbox() {
        return groupFilterCbox;
    }

    public void setSortCbox(JComboBox<String> SortCbox) {
        this.sortCbox = SortCbox;
    }

    public void setTblofStd(JTable TblofStd) {
        this.TblofStd = TblofStd;
    }

    public void setULvlFilterCbox(JComboBox<String> ULvlFilterCbox) {
        this.userLvlFilterCbox = ULvlFilterCbox;
    }

    public void setGroupFilterCbox(JComboBox<String> groupFilterCbox) {
        this.groupFilterCbox = groupFilterCbox;
    }

    public JPanel getUListContent() {
        return userListContent;
    }

    public JButton getResetBttn() {
        return resetBttn;
    }

    public void setResetBttn(JButton resetBttn) {
        this.resetBttn = resetBttn;
    }
    

    /**
     * fills the table with all the students
     * @author Amit
     */
    public void fillTable()
    {
        UserMDL.getConnection();
        ArrayList<String> resultQuery = UserMDL.queryData("SELECT user_lang_lvl, user_id, user_name, user_group_id, user_progresspoints FROM User WHERE user_type = 'Student'");
       
        String[] columnNames = {"Lvl", "Student ID", "Student Name", "Group ID", "Points"};
        int row = resultQuery.size()/columnNames.length;
        String[][] data = new String[row][columnNames.length];
        
        int count = 0;
        for (int i = 0; i < data.length; i++) 
        {
            for (int j = 0; j < columnNames.length; j++) 
            {
                data[i][j] = resultQuery.get(count);
                count++;
            }
            
        }
        
        DefaultTableModel td = new DefaultTableModel(data, columnNames)
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
                    
        };
        getTblofStd().setModel(td);
    }
    
    /**
     * fills the combo box with user's group id, language level
     * @author Amit
     */
    public void fillCombo()
    {
        String query;
        
        //user group id
        query = "SELECT DISTINCT user_group_id FROM User WHERE user_type = 'Student'";
        UserMDL.getConnection();
        ArrayList<String> result = UserMDL.queryData(query);
        
        
        for (int i = 0; i < result.size(); i++) 
        {
            getGroupFilterCbox().addItem(result.get(i));
        }
        
        
        //user lang level
        query = "SELECT DISTINCT user_lang_lvl FROM User";
        result = UserMDL.queryData(query);
        
        for (int i = 0; i < result.size(); i++) 
        {
            getULvlFilterCbox().addItem(result.get(i));;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblofStd;
    private javax.swing.JComboBox<String> groupFilterCbox;
    private javax.swing.JLabel groupSelectLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderByLbl;
    private javax.swing.JButton resetBttn;
    private javax.swing.JComboBox<String> sortCbox;
    private javax.swing.JPanel userListContent;
    private javax.swing.JComboBox<String> userLvlFilterCbox;
    private javax.swing.JLabel userLvlLbl;
    // End of variables declaration//GEN-END:variables

}
